python3.10 main.py \
    --image_dir ../code/r2genRl-ophthalmology/data/ffa_ir/FFAIR/ \
    --ann_path data/ffa_ir/ffair_annotation6.json \
    --dataset_name ffa_ir \
    --max_seq_length 80 \
    --threshold 4 \
    --batch_size 6 \
    --epochs 100 \
    --save_dir result \
    --step_size 50 \
    --gamma 0.1 \
    --seed 9223
