python3.10 main.py \
--image_dir data/images/ \
--ann_path data/annotation.json \
--dataset_name iu_xray \
--max_seq_length 60 \
--threshold 3 \
--batch_size 16 \
--epochs 100 \
--save_dir result \
--step_size 50 \
--gamma 0.1 \
--seed 9223